#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fediprofile"
name = "FediProfile"
description.en = "The open-source, federated alternative to Linktree."
description.fr = "L'alternative open source et fédérée à Linktree."

version = "0.0.2~ynh1"

maintainers = ["grossermensch"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://hub.vocalcat.com"
admindoc = "https://github.com/tryvocalcat/fediprofile/blob/main/README.md"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
# FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = false

sso = false

disk = "500M"
ram.build = "500M"
ram.runtime = "150M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/tryvocalcat/fediprofile/archive/refs/tags/0.0.2.tar.gz"
    sha256 = "282eec135258d8b70cf29f2e9967349f05a596cc855f76523c1990df26651b0f"
    # Careful, this autoupdate does not put the right asset, it only serves as a notification!
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset = "tarball"
    autoupdate.needs_manual_tweaks = true

    [resources.sources.dotnet]
    amd64.url = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-x64.tar.gz"
    amd64.sha256 = "9c72253df8cbdbc775c76d6dcefc057aabb0bf7c978e5c3f24ab0afed839fd1f"
    arm64.url = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-arm64.tar.gz"
    arm64.sha256 = "d039cbb3ef822aad0226857c1d89763c9c2a4bf339015bb11c99a7f6e62d3062"
    armhf.url = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-arm.tar.gz"
    armhf.sha256 = "6ef6521e262d05302f3e52026d59b8464ae881fc983671c20e3a9e4034d7a99c"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5000

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = "mariadb-server, deb1, deb2, php8.3-foo, php8.3-bar"

    [resources.database]
    # This will automatically provision/deprovison a MySQL DB and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    type = "mysql"
